---
- name: Update system and notify via Discord
  hosts: all
  become: yes
  
  tasks:
    - name: Update system (Debian-based)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    - name: Update system (RHEL-based)
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Clean packages (RHEL-based)
      ansible.builtin.command: dnf autoremove -y
      when: ansible_os_family == "RedHat"

    - name: Get current local time
      set_fact:
        current_local_time: "{{ lookup('pipe', 'date +\"%d. %m. %Y, %H:%M:%S\"') }}"
      run_once: true
      delegate_to: 127.0.0.1

    - name: Send Discord notification
      ansible.builtin.uri:
        url: "{{ DISCORD_WEBHOOK }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          content: |
            ✅ **Aktualizace úspěšná**
            Aktualizované stroje:
            {% for host in play_hosts %}
            • `{{ host }}`
            {% endfor %}
            Čas: **{{ current_local_time }}**
        status_code: 204
      delegate_to: 127.0.0.1
      run_once: true
      become: false
