---
- name: Update system and notify via Discord
  hosts: all
  become: yes
  
  tasks:
    - name: Update system (Debian-based)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    - name: Update system (RHEL-based)
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Clean packages (RHEL-based)
      ansible.builtin.command: dnf autoremove -y
      when: ansible_os_family == "RedHat"

    - name: Send Discord notification
      ansible.builtin.uri:
        url: "{{ DISCORD_WEBHOOK }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          content: ":white_check_mark: Update complete on all hosts at {{ ansible_date_time.iso8601 }}."
      delegate_to: 127.0.0.1
      run_once: true
      become: false

